In [ ]:
# Loading Dataset
import pandas as pd
df=pd.read_csv(r"C:\Users\SPTINT-20\Downloads\Heart_disease.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [14]:
df.head(4)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1

In [15]:
# Encoding categorical columns
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=df.apply(lambda x:le.fit_transform(x))
df.head(4)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,12,1,1,41,147,0,1,98,0,10,2,0
1,21,0,2,55,40,0,1,82,0,20,1,1
2,9,1,1,31,141,0,2,25,0,10,2,0
3,20,0,0,39,72,0,1,34,1,25,1,1

In [16]:
x=df.drop(['HeartDisease'],axis=1)
y=df['HeartDisease']

In [17]:
# splitting Dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [24]:
# Scaling features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [25]:
# importing model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [26]:
# Training model
model.fit(x_train,y_train)

LogisticRegression()

In [27]:
y_pred = model.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Confusion Matrics:\n",confusion_matrix(y_test,y_pred))
print("accuracy_score:",accuracy_score(y_test,y_pred)*100)

Confusion Matrics:
 [[68  9]
 [21 86]]
accuracy_score: 83.69565217391305